PARAMETER PROCKAPNEWSCALE(PROC)  "Relationship at PROC between coming (index 3) and leaving (index 4) FLOW; interior PROC only"
                                                                                                                               
/                                                                                                                              
                                                                                                                               
                                                                                                                               
/;                                                                                                                             
