PARAMETER MINFLOW(YYY,CCCRRRAAA,PROC,FLOW) "Constraint about fuel use limitations (U/year)"                                                                                  
/                                                                                                                                                                            
                                                                                                                                                                             
2050                                                                                           	.    AUSTRIA        .    RoadBuffer .    ROADFLOW 6231272.72727273            
2050                                                                                           	.    BELGIUM        .    RoadBuffer .    ROADFLOW 4673454.54545455            
2050                                                                                           	.    BULGARIA       .    RoadBuffer .    ROADFLOW 3226909.09090909            
2050                                                                                           	.    CROATIA        .    RoadBuffer .    ROADFLOW 1446545.45454545            
2050                                                                                           	.    CYPRUS         .    RoadBuffer .    ROADFLOW 222545.454545455            
2050                                                                                           	.    CZECH_REPUBLIC .    RoadBuffer .    ROADFLOW 6342545.45454545            
2050                                                                                           	.    DENMARK        .    RoadBuffer .    ROADFLOW 5229818.18181818            
2050                                                                                           	.    ESTONIA        .    RoadBuffer .    ROADFLOW 778909.090909091            
2050                                                                                           	.    FINLAND        .    RoadBuffer .    ROADFLOW 6453818.18181818            
2050                                                                                           	.    FRANCE         .    RoadBuffer .    ROADFLOW 46178181.8181818            
2050                                                                                           	.    GERMANY        .    RoadBuffer .    ROADFLOW 46178181.8181818            
2050                                                                                           	.    GREECE         .    RoadBuffer .    ROADFLOW 4228363.63636364            
2050                                                                                           	.    HUNGARY        .    RoadBuffer .    ROADFLOW 6787636.36363636            
2050                                                                                           	.    IRELAND        .    RoadBuffer .    ROADFLOW 12462545.4545455            
2050                                                                                           	.    ITALY          .    RoadBuffer .    ROADFLOW 26037818.1818182            
2050                                                                                           	.    LATVIA         .    RoadBuffer .    ROADFLOW 1669090.90909091            
2050                                                                                           	.    LITHUANIA      .    RoadBuffer .    ROADFLOW 2448000                     
2050                                                                                           	.    LUXEMBOURG     .    RoadBuffer .    ROADFLOW 2114181.81818182            
2050                                                                                           	.    MALTA          .    RoadBuffer .    ROADFLOW 1335272.72727273            
2050                                                                                           	.    NETHERLANDS    .    RoadBuffer .    ROADFLOW 12017454.5454545            
2050                                                                                           	.    NORWAY         .    RoadBuffer .    ROADFLOW 8901818.18181818            
2050                                                                                           	.    POLAND         .    RoadBuffer .    ROADFLOW 29598545.4545455            
2050                                                                                           	.    PORTUGAL       .    RoadBuffer .    ROADFLOW 4562181.81818182            
2050                                                                                           	.    ROMANIA        .    RoadBuffer .    ROADFLOW 4673454.54545455            
2050                                                                                           	.    SLOVAKIA       .    RoadBuffer .    ROADFLOW 4562181.81818182            
2050                                                                                           	.    SLOVENIA       .    RoadBuffer .    ROADFLOW 1780363.63636364            
2050                                                                                           	.    SPAIN          .    RoadBuffer .    ROADFLOW 26371636.3636364            
2050                                                                                           	.    SWEDEN         .    RoadBuffer .    ROADFLOW 8790545.45454546            
2050                                                                                           	.    SWITZERLAND    .    RoadBuffer .    ROADFLOW 5563636.36363636            
2050                                                                                           	.    UNITED_KINGDOM .    RoadBuffer .    ROADFLOW 40837090.9090909            
                                                                                                                                                                             
2050                                                                                           	.    BELGIUM        .    SeaBuffer  .    SEAFLOW  317326219.698184            
2050                                                                                           	.    BULGARIA       .    SeaBuffer  .    SEAFLOW  3140499.73911383            
2050                                                                                           	.    CROATIA        .    SeaBuffer  .    SEAFLOW  183047.738436622            
2050                                                                                           	.    DENMARK        .    SeaBuffer  .    SEAFLOW  32647423.651907             
2050                                                                                           	.    ESTONIA        .    SeaBuffer  .    SEAFLOW  14022996.1807844            
2050                                                                                           	.    FINLAND        .    SeaBuffer  .    SEAFLOW  13689668.2463269            
2050                                                                                           	.    FRANCE         .    SeaBuffer  .    SEAFLOW  70755737.6542192            
2050                                                                                           	.    GERMANY        .    SeaBuffer  .    SEAFLOW  102920279.237979            
2050                                                                                           	.    GREECE         .    SeaBuffer  .    SEAFLOW  86599869.0012324            
2050                                                                                           	.    IRELAND        .    SeaBuffer  .    SEAFLOW  7281149.19483249            
2050                                                                                           	.    ITALY          .    SeaBuffer  .    SEAFLOW  93907701.5160717            
2050                                                                                           	.    LATVIA         .    SeaBuffer  .    SEAFLOW  11043323.8618023            
2050                                                                                           	.    LITHUANIA      .    SeaBuffer  .    SEAFLOW  7230622.01940513            
2050                                                                                           	.    NETHERLANDS    .    SeaBuffer  .    SEAFLOW  490418941.716799            
2050                                                                                           	.    POLAND         .    SeaBuffer  .    SEAFLOW  11505807.3714391            
2050                                                                                           	.    PORTUGAL       .    SeaBuffer  .    SEAFLOW  31152817.2199078            
2050                                                                                           	.    ROMANIA        .    SeaBuffer  .    SEAFLOW  1645638.78176853            
2050                                                                                           	.    SLOVENIA       .    SeaBuffer  .    SEAFLOW  6714234.93662819            
2050                                                                                           	.    SPAIN          .    SeaBuffer  .    SEAFLOW  270984904.180681            
2050                                                                                           	.    SWEDEN         .    SeaBuffer  .    SEAFLOW  99080377.6620246            
2050                                                                                           	.    NORWAY         .    SeaBuffer  .    SEAFLOW  107601351.300575            
2050                                                                                           	.    UNITED_KINGDOM .    SeaBuffer  .    SEAFLOW  199149599.110979            
                                                                                                                                                                             
2050                                                                                           	.    AUSTRIA        .    AirBuffer  .    AIRFLOW  30246748.8702877            
2050                                                                                           	.    BELGIUM        .    AirBuffer  .    AIRFLOW  64377313.8735709            
2050                                                                                           	.    BULGARIA       .    AirBuffer  .    AIRFLOW  10136421.6815753            
2050                                                                                           	.    CROATIA        .    AirBuffer  .    AIRFLOW  6621707.13514397            
2050                                                                                           	.    CZECH_REPUBLIC .    AirBuffer  .    AIRFLOW  14155212.9461132            
2050                                                                                           	.    DENMARK        .    AirBuffer  .    AIRFLOW  42299122.3757724            
2050                                                                                           	.    ESTONIA        .    AirBuffer  .    AIRFLOW  2362011.92788994            
2050                                                                                           	.    FINLAND        .    AirBuffer  .    AIRFLOW  26114567.1679909            
2050                                                                                           	.    FRANCE         .    AirBuffer  .    AIRFLOW  260467039.621141            
2050                                                                                           	.    GERMANY        .    AirBuffer  .    AIRFLOW  386339416.382752            
2050                                                                                           	.    GREECE         .    AirBuffer  .    AIRFLOW  42760235.3765244            
2050                                                                                           	.    HUNGARY        .    AirBuffer  .    AIRFLOW  9341116.41980787            
2050                                                                                           	.    IRELAND        .    AirBuffer  .    AIRFLOW  38119761.9645872            
2050                                                                                           	.    ITALY          .    AirBuffer  .    AIRFLOW  151990833.362545            
2050                                                                                           	.    LATVIA         .    AirBuffer  .    AIRFLOW  5431138.41233335            
2050                                                                                           	.    LITHUANIA      .    AirBuffer  .    AIRFLOW  4259847.18409124            
2050                                                                                           	.    LUXEMBOURG     .    AirBuffer  .    AIRFLOW  21807789.1327791            
2050                                                                                           	.    NETHERLANDS    .    AirBuffer  .    AIRFLOW  162851023.420083            
2050                                                                                           	.    POLAND         .    AirBuffer  .    AIRFLOW  33460003.7730277            
2050                                                                                           	.    PORTUGAL       .    AirBuffer  .    AIRFLOW  49431229.1599507            
2050                                                                                           	.    ROMANIA        .    AirBuffer  .    AIRFLOW  14352017.2653648            
2050                                                                                           	.    SLOVAKIA       .    AirBuffer  .    AIRFLOW  1635465.1298714             
2050                                                                                           	.    SLOVENIA       .    AirBuffer  .    AIRFLOW  987863.005322105            
2050                                                                                           	.    SPAIN          .    AirBuffer  .    AIRFLOW  202271838.174599            
2050                                                                                           	.    SWEDEN         .    AirBuffer  .    AIRFLOW  33731514.9884097            
2050                                                                                           	.    NORWAY         .    AirBuffer  .    AIRFLOW  36182971.7609654            
2050                                                                                           	.    SWITZERLAND    .    AirBuffer  .    AIRFLOW  48533648.0612454            
2050                                                                                           	.    UNITED_KINGDOM .    AirBuffer  .    AIRFLOW  183721200.889021            
                                                                                                                                                                             
2050																							.	AUSTRIA			.	GasBuffer	.	GASFLOW	7906000
2050																							.	BELGIUM			.	GasBuffer	.	GASFLOW	10935000
2050																							.	BULGARIA		.	GasBuffer	.	GASFLOW	1892000
2050																							.	CROATIA			.	GasBuffer	.	GASFLOW	3092000
2050																							.	CZECH_REPUBLIC	.	GasBuffer	.	GASFLOW	25021000
2050																							.	DENMARK			.	GasBuffer	.	GASFLOW	31738000
2050																							.	ESTONIA			.	GasBuffer	.	GASFLOW	600000
2050																							.	FINLAND			.	GasBuffer	.	GASFLOW	8182000
2050																							.	FRANCE			.	GasBuffer	.	GASFLOW	79131000
2050																							.	GERMANY			.	GasBuffer	.	GASFLOW	324188000
2050																							.	GREECE			.	GasBuffer	.	GASFLOW	6496000
2050																							.	HUNGARY			.	GasBuffer	.	GASFLOW	3728000
2050																							.	IRELAND			.	GasBuffer	.	GASFLOW	2161000
2050																							.	ITALY			.	GasBuffer	.	GASFLOW	84236000
2050																							.	LATVIA			.	GasBuffer	.	GASFLOW	1797000
2050																							.	LUXEMBOURG		.	GasBuffer	.	GASFLOW	723000
2050																							.	LITHUANIA		.	GasBuffer	.	GASFLOW	1638000
2050																							.	NETHERLANDS		.	GasBuffer	.	GASFLOW	19100000
2050																							.	NORWAY			.	GasBuffer	.	GASFLOW	2897000
2050																							.	POLAND			.	GasBuffer	.	GASFLOW	15748000
2050																							.	PORTUGAL		.	GasBuffer	.	GASFLOW	3991000
2050																							.	ROMANIA			.	GasBuffer	.	GASFLOW	765000
2050																							.	SLOVAKIA		.	GasBuffer	.	GASFLOW	4400000
2050																							.	SLOVENIA		.	GasBuffer	.	GASFLOW	960000
2050																							.	SPAIN			.	GasBuffer	.	GASFLOW	14309000
2050																							.	SWEDEN			.	GasBuffer	.	GASFLOW	7448000
2050																							.	SWITZERLAND		.	GasBuffer	.	GASFLOW	7906000
2050																							.	UNITED_KINGDOM	.	GasBuffer	.	GASFLOW	114931000                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                             
/;                                                                                                                                                                           
                                                                                                                                                                             
*MINFLOW(YYY,CCCRRRAAA,PROC,FLOW) = MINFLOW('2020',CCCRRRAAA,PROC,FLOW);                                                                                                     
                                                                                                                                                                             
MINFLOW('2030',C,PROC,FLOW)$(MINFLOW('2050',C,PROC,FLOW)) = MINFLOW('2050',C,PROC,FLOW) * 0.1;                                                                               
MINFLOW('2040',C,PROC,FLOW)$(MINFLOW('2050',C,PROC,FLOW)) = MINFLOW('2050',C,PROC,FLOW) * 0.4;                                                                               
MINFLOW(Y,C,'GasBuffer','GASFLOW')$(MINFLOW('2050',C,'GasBuffer','GASFLOW')) = MINFLOW('2050',C,'GasBuffer','GASFLOW');