SET AAAOPTIFLOW(AAA)     'Areas that are used in the OptiFLow calculations'
                                                                           
                                                                           
/                                                                          
                                                                           
/;                                                                         
