SET PROCSOURCE(PROC) "Start PROC (no trace entering)"
/                                                    
                                                     
CO2_Source_FOSSIL                                    
CO2_Source_BIOGEN                                    
CO2_Source_DAC                                       
                                                     
HydrogenSource_MWh                                   
                                                     
Wood_Gen                                             
Straw_Gen                                            
Muni_Waste_Gen                                       
Wood_Pellets_Gen                                     
Manure_Gen                                           
Deep_Litter_Gen                                      
Food_Waste_Gen                                       
Nature_Area_Gen                                      
Other_Gas_Gen                                        
DieselSource                                         
MDOSource                                            
KeroseneSource                                       
BioLiquid_Import                                     
NorthSeaGas                                          
/;                                                   
