TABLE PROCDATA(PROC,PROCDATASET)    "Process data"                                                                                                                    
                                                                                                                                                                      
*                                                           MEuro/GJ/h                                                    Euro/GJ/h                                   
                                                            PROCINVCOST         PROCKAPVARIABLE PROCFROMYEAR PROCLIFETIME PROCFIXCOST      /*   PROCVARCOST */        
                                                                                                                                                                      
*BiogasProd_single                                          0.395               1               2020         20           7170                                        
*BiogasProd_mix                                             0.307               1               2020         20           2812                                        
*BiogasProd_mix                                             0.42                1               2020         20           0.001                                       
*BiogasProd_mix                                             0.307               1               2020         20           2812                                        
                                                                                                                                                                      
BiogasUpgr_BMETH_20                                         0.118               1               2020         20           2944                                        
BiogasUpgr_BMETH_25                                         0.112               1               2025         20           2792                                        
BiogasUpgr_BMETH_30                                         0.106               1               2030         20           2639                                        
BiogasUpgr_BMETH_35                                         0.103               1               2035         20           2576                                        
BiogasUpgr_BMETH_40                                         0.1                 1               2040         20           2514                                        
BiogasUpgr_BMETH_45                                         0.098               1               2045         20           2451                                        
BiogasUpgr_BMETH_50                                         0.095               1               2050         20           2389                                        
                                                                                                                                                                      
BIOGAS_GRID_STO                                             0.0059085           1               2020         20           59.085                                      
                                                                                                                                                                      
Straw_pre_BG_20                                             5.19042609717E-005  1               2020         20           0.001                                       
Straw_pre_BG_25                                             4.930904792312E-005 1               2025         20           0.001                                       
Straw_pre_BG_30                                             4.671383487453E-005 1               2030         20           0.001                                       
Straw_pre_BG_35                                             4.554598900267E-005 1               2035         20           0.001                                       
Straw_pre_BG_40                                             4.437814313081E-005 1               2040         20           0.001                                       
Straw_pre_BG_45                                             4.321029725894E-005 1               2045         20           0.001                                       
Straw_pre_BG_50                                             4.204245138708E-005 1               2050         20           0.001                                       
                                                                                                                                                                      
Deep_Litter_pre_BG_20                                       1.88303830502E-005  1               2020         20           0.001                                       
Deep_Litter_pre_BG_25                                       1.788886389769E-005 1               2025         20           0.001                                       
Deep_Litter_pre_BG_30                                       1.694734474518E-005 1               2030         20           0.001                                       
Deep_Litter_pre_BG_35                                       1.65E-005           1               2035         20           0.001                                       
Deep_Litter_pre_BG_40                                       1.61E-005           1               2040         20           0.001                                       
Deep_Litter_pre_BG_45                                       1.57E-005           1               2045         20           0.001                                       
Deep_Litter_pre_BG_50                                       1.53E-005           1               2050         20           0.001                                       
                                                                                                                                                                      
Food_Waste_pre_BG_20                                        2.112382713965E-005 1               2020         20           0.001                                       
Food_Waste_pre_BG_25                                        2.006763578266E-005 1               2025         20           0.001                                       
Food_Waste_pre_BG_30                                        1.901144442568E-005 1               2030         20           0.001                                       
Food_Waste_pre_BG_35                                        1.548074760377E-005 1               2035         20           0.001                                       
Food_Waste_pre_BG_40                                        1.195005078186E-005 1               2040         20           0.001                                       
Food_Waste_pre_BG_45                                        8.419353959945E-006 1               2045         20           0.001                                       
Food_Waste_pre_BG_50                                        4.888657138032E-006 1               2050         20           0.001                                       
                                                                                                                                                                      
Nature_Area_pre_BG_20                                       3.621227509654E-005 1               2020         20           0.001                                       
Nature_Area_pre_BG_25                                       3.440166134171E-005 1               2025         20           0.001                                       
Nature_Area_pre_BG_30                                       3.259104758688E-005 1               2030         20           0.001                                       
Nature_Area_pre_BG_35                                       3.177627139721E-005 1               2035         20           0.001                                       
Nature_Area_pre_BG_40                                       3.096149520754E-005 1               2040         20           0.001                                       
Nature_Area_pre_BG_45                                       3.014671901787E-005 1               2045         20           0.001                                       
Nature_Area_pre_BG_50                                       2.933194282819E-005 1               2050         20           0.001                                       
                                                                                                                                                                      
Manure_tank_20                                              1.569198587517E-005 1               2020         20           0.001                                       
Manure_tank_25                                              1.490738658141E-005 1               2025         20           0.001                                       
Manure_tank_30                                              1.412278728765E-005 1               2030         20           0.001                                       
Manure_tank_35                                              1.376971760546E-005 1               2035         20           0.001                                       
Manure_tank_40                                              1.341664792327E-005 1               2040         20           0.001                                       
Manure_tank_45                                              1.306357824108E-005 1               2045         20           0.001                                       
Manure_tank_50                                              1.271050855888E-005 1               2050         20           0.001                                       
                                                                                                                                                                      
                                                                                                                                                                      
*BiogasProd_mix                                             3.23E-005           1               2020         20           2.9                                         
                                                                                                                                                                      
CO2_DAC_20                                                  5.8                 1               2020         30           210000                                      
CO2_DAC_25                                                  4.3                 1               2025         30           160000                                      
CO2_DAC_30                                                  2.7                 1               2030         30           100000                                      
CO2_DAC_35                                                  2.3                 1               2035         30           85000                                       
CO2_DAC_40                                                  1.9                 1               2040         30           70000                                       
CO2_DAC_45                                                  1.75                1               2045         30           65000                                       
CO2_DAC_50                                                  1.6                 1               2050         30           60000                                       
                                                                                                                                                                      
CO2_Bio_20                                                  0.325               1               2020         25           11915                                       
CO2_Bio_25                                                  0.321               1               2025         25           11915                                       
CO2_Bio_30                                                  0.317               1               2030         25           11915                                       
CO2_Bio_35                                                  0.313               1               2035         25           11915                                       
CO2_Bio_40                                                  0.308               1               2040         25           11915                                       
CO2_Bio_45                                                  0.304               1               2045         25           11915                                       
CO2_Bio_50                                                  0.3                 1               2050         25           11915                                       
                                                                                                                                                                      
CO2_Sto                                                     1.521               1               2020         30           30435                                       
*****gasification                                                                                                                                                     
TG_20                                                       0.234516737109375   1               2020         30           9394.07044078125 /*   0.953       TJEK */   
TG_25                                                       0.2233492734375     1               2025         30           8946.733753125   /*   0.953       TJEK */   
TG_30                                                       0.21271359375       1               2030         30           8520.6988125     /*   0.953       TJEK */   
TG_35                                                       0.202584375         1               2035         30           8114.95125       /*   0.953       TJEK */   
TG_40                                                       0.1929375           1               2040         30           7728.525         /*   0.953       TJEK */   
TG_45                                                       0.18375             1               2045         30           7360.5           /*   0.953       TJEK */   
TG_50                                                       0.175               1               2050         30           7010             /*   0.953       TJEK */   
                                                                                                                                                                      
                                                                                                                                                                      
***********************meth                                                                                                                                           
                                                                                                                                                                      
Methanol_synthesis_TG_20                                    0.0657789024849398  1               2020         30           1973.36707454819                            
Methanol_synthesis_TG_25                                    0.0626465737951807  1               2025         30           1879.39721385542                            
Methanol_synthesis_TG_30                                    0.0596634036144578  1               2030         30           1789.90210843374                            
Methanol_synthesis_TG_35                                    0.0568222891566265  1               2035         30           1704.6686746988                             
Methanol_synthesis_TG_40                                    0.0541164658634538  1               2040         30           1623.49397590361                            
Methanol_synthesis_TG_45                                    0.0515394912985274  1               2045         30           1546.18473895582                            
Methanol_synthesis_TG_50                                    0.0490852298081214  1               2050         30           1472.55689424364                            
                                                                                                                                                                      
*******Biojet                                                                                                                                                         
BioJet_20                                                   0.351               1               2020         30           10483                                       
BioJet_25                                                   0.334               1               2025         30           9959                                        
BioJet_30                                                   0.317               1               2030         30           9461                                        
BioJet_35                                                   0.301               1               2035         30           8988                                        
BioJet_40                                                   0.286               1               2040         30           8539                                        
BioJet_45                                                   0.272               1               2045         30           8112                                        
BioJet_50                                                   0.258               1               2050         30           7706                                        
                                                                                                                                                                      
BioJet_H2_20                                                0.3861              1               2020         30           11531.3                                     
BioJet_H2_25                                                0.3674              1               2025         30           10954.9                                     
BioJet_H2_30                                                0.3487              1               2030         30           10407.1                                     
BioJet_H2_35                                                0.3311              1               2035         30           9886.8                                      
BioJet_H2_40                                                0.3146              1               2040         30           9392.9                                      
BioJet_H2_45                                                0.2992              1               2045         30           8923.2                                      
BioJet_H2_50                                                0.2838              1               2050         30           8476.6                                      
                                                                                                                                                                      
EMethanol_synthesis_20                                      0.235               1               2020         30           9402                                        
EMethanol_synthesis_25                                      0.188               1               2025         30           7521                                        
EMethanol_synthesis_30                                      0.141               1               2030         30           5641                                        
EMethanol_synthesis_35                                      0.141               1               2035         30           5641                                        
EMethanol_synthesis_40                                      0.141               1               2040         30           5641                                        
EMethanol_synthesis_45                                      0.141               1               2045         30           5641                                        
EMethanol_synthesis_50                                      0.141               1               2050         30           5641                                        
                                                                                                                                                                      
EMethanol_Upgrade_20                                        0.0915570046861632  1               2020         30           3252                                        
EMethanol_Upgrade_25                                        0.08976176930016    1               2025         30           3252                                        
EMethanol_Upgrade_30                                        0.088001734608      1               2030         30           3252                                        
EMethanol_Upgrade_35                                        0.0862762104        1               2035         30           3252                                        
EMethanol_Upgrade_40                                        0.08458452          1               2040         30           3252                                        
EMethanol_Upgrade_45                                        0.082926            1               2045         30           3252                                        
EMethanol_Upgrade_50                                        0.0813              1               2050         30           3252                                        
                                                                                                                                                                      
E_FT_20                                                     0.214               1               2020         30           8547                                        
E_FT_25                                                     0.175               1               2025         30           7007                                        
E_FT_30                                                     0.137               1               2030         30           5467                                        
E_FT_35                                                     0.137               1               2035         30           5467                                        
E_FT_40                                                     0.137               1               2040         30           5467                                        
E_FT_45                                                     0.137               1               2045         30           5467                                        
E_FT_50                                                     0.137               1               2050         30           5467                                        
                                                                                                                                                                      
Ammonia_Synthesis_20                                        0.2605145925375     1               2020         30           5716.80963339062                            
Ammonia_Synthesis_25                                        0.24810913575       1               2025         30           6017.6943509375                             
Ammonia_Synthesis_30                                        0.236294415         1               2030         30           6334.41510625                               
Ammonia_Synthesis_35                                        0.2250423           1               2035         30           6667.805375                                 
Ammonia_Synthesis_40                                        0.214326            1               2040         30           7018.7425                                   
Ammonia_Synthesis_45                                        0.20412             1               2045         30           7388.15                                     
Ammonia_Synthesis_50                                        0.1944              1               2050         30           7777                                        
                                                                                                                                                                      
;                                                                                                                                                                     
                                                                                                                                                                      
*PROCDATA(PROC,'PROCINVCOST')=PROCDATA(PROC,'PROCINVCOST');                                                                                                           
