SET  PROCKAPDATA(YYY,PROC,FLOW,IFLOWINOUT)    "Process data: capacity relative to FLOW and in/out direction ()"                                                                       
/                                                                                                                                                                                     
*2020                                                                                                           .    ProA                     .    ResProA         .    IFLOWINOUT_IN 
*2020                                                                                                           .    StoA                     .    ProStoA         .    IFLOWINOUT_IN 
*2020                                                                                                           .    ProB                     .    ResProB         .    IFLOWINOUT_IN 
                                                                                                                                                                                      
*2020                                                                                                           .    ProD                     .    ResProD         .    IFLOWINOUT_IN 
*2020                                                                                                           .    StoD                     .    ProStoD         .    IFLOWINOUT_IN 
                                                                                                                                                                                      
                                                                                                                                                                                      
                                                                                                                                                                                      
2020                                                                                                            .    Manure_tank_20           .    MANURE_GEN_FLOW .    IFLOWINOUT_IN 
2020                                                                                                            .    Manure_tank_25           .    MANURE_GEN_FLOW .    IFLOWINOUT_IN 
2020                                                                                                            .    Manure_tank_30           .    MANURE_GEN_FLOW .    IFLOWINOUT_IN 
2020                                                                                                            .    Manure_tank_35           .    MANURE_GEN_FLOW .    IFLOWINOUT_IN 
2020                                                                                                            .    Manure_tank_40           .    MANURE_GEN_FLOW .    IFLOWINOUT_IN 
2020                                                                                                            .    Manure_tank_45           .    MANURE_GEN_FLOW .    IFLOWINOUT_IN 
2020                                                                                                            .    Manure_tank_50           .    MANURE_GEN_FLOW .    IFLOWINOUT_IN 
                                                                                                                                                                                      
                                                                                                                                                                                      
2020                                                                                                            .    Biogas_Grid_STO          .    BIOGAS_FLOW     .    IFLOWINOUT_IN 
                                                                                                                                                                                      
2020                                                                                                            .    BiogasUpgr_BMETH_20      .    BIOGAS_FLOW     .    IFLOWINOUT_IN 
2020                                                                                                            .    BiogasUpgr_BMETH_25      .    BIOGAS_FLOW     .    IFLOWINOUT_IN 
2020                                                                                                            .    BiogasUpgr_BMETH_30      .    BIOGAS_FLOW     .    IFLOWINOUT_IN 
2020                                                                                                            .    BiogasUpgr_BMETH_35      .    BIOGAS_FLOW     .    IFLOWINOUT_IN 
2020                                                                                                            .    BiogasUpgr_BMETH_40      .    BIOGAS_FLOW     .    IFLOWINOUT_IN 
2020                                                                                                            .    BiogasUpgr_BMETH_45      .    BIOGAS_FLOW     .    IFLOWINOUT_IN 
2020                                                                                                            .    BiogasUpgr_BMETH_50      .    BIOGAS_FLOW     .    IFLOWINOUT_IN 
                                                                                                                                                                                      
                                                                                                                                                                                      
2020                                                                                                            .    CO2_DAC_20               .    CO2_FLOW_DAC    .    IFLOWINOUT_OUT
2020                                                                                                            .    CO2_DAC_25               .    CO2_FLOW_DAC    .    IFLOWINOUT_OUT
2020                                                                                                            .    CO2_DAC_30               .    CO2_FLOW_DAC    .    IFLOWINOUT_OUT
2020                                                                                                            .    CO2_DAC_35               .    CO2_FLOW_DAC    .    IFLOWINOUT_OUT
2020                                                                                                            .    CO2_DAC_40               .    CO2_FLOW_DAC    .    IFLOWINOUT_OUT
2020                                                                                                            .    CO2_DAC_45               .    CO2_FLOW_DAC    .    IFLOWINOUT_OUT
2020                                                                                                            .    CO2_DAC_50               .    CO2_FLOW_DAC    .    IFLOWINOUT_OUT
                                                                                                                                                                                      
2020                                                                                                            .    CO2_Bio_20               .    CO2_FLOW_BIO    .    IFLOWINOUT_OUT
2020                                                                                                            .    CO2_Bio_25               .    CO2_FLOW_BIO    .    IFLOWINOUT_OUT
2020                                                                                                            .    CO2_Bio_30               .    CO2_FLOW_BIO    .    IFLOWINOUT_OUT
2020                                                                                                            .    CO2_Bio_35               .    CO2_FLOW_BIO    .    IFLOWINOUT_OUT
2020                                                                                                            .    CO2_Bio_40               .    CO2_FLOW_BIO    .    IFLOWINOUT_OUT
2020                                                                                                            .    CO2_Bio_45               .    CO2_FLOW_BIO    .    IFLOWINOUT_OUT
2020                                                                                                            .    CO2_Bio_50               .    CO2_FLOW_BIO    .    IFLOWINOUT_OUT
                                                                                                                                                                                      
2020                                                                                                            .    CO2_Sto                  .    CO2_FLOW_STO    .    IFLOWINOUT_IN 
                                                                                                                                                                                      
2020                                                                                                            .    TG_20                    .    BIOMASS_TG      .    IFLOWINOUT_IN 
2020                                                                                                            .    TG_25                    .    BIOMASS_TG      .    IFLOWINOUT_IN 
2020                                                                                                            .    TG_30                    .    BIOMASS_TG      .    IFLOWINOUT_IN 
2020                                                                                                            .    TG_35                    .    BIOMASS_TG      .    IFLOWINOUT_IN 
2020                                                                                                            .    TG_40                    .    BIOMASS_TG      .    IFLOWINOUT_IN 
2020                                                                                                            .    TG_45                    .    BIOMASS_TG      .    IFLOWINOUT_IN 
2020                                                                                                            .    TG_50                    .    BIOMASS_TG      .    IFLOWINOUT_IN 
                                                                                                                                                                                      
                                                                                                                                                                                      
                                                                                                                                                                                      
                                                                                                                                                                                      
                                                                                                                                                                                      
2020                                                                                                            .    Methanol_synthesis_TG_20 .    BIO_ME_FLOW     .    IFLOWINOUT_IN 
2020                                                                                                            .    Methanol_synthesis_TG_25 .    BIO_ME_FLOW     .    IFLOWINOUT_IN 
2020                                                                                                            .    Methanol_synthesis_TG_30 .    BIO_ME_FLOW     .    IFLOWINOUT_IN 
2020                                                                                                            .    Methanol_synthesis_TG_35 .    BIO_ME_FLOW     .    IFLOWINOUT_IN 
2020                                                                                                            .    Methanol_synthesis_TG_40 .    BIO_ME_FLOW     .    IFLOWINOUT_IN 
2020                                                                                                            .    Methanol_synthesis_TG_45 .    BIO_ME_FLOW     .    IFLOWINOUT_IN 
2020                                                                                                            .    Methanol_synthesis_TG_50 .    BIO_ME_FLOW     .    IFLOWINOUT_IN 
                                                                                                                                                                                      
                                                                                                                                                                                      
                                                                                                                                                                                      
*******Biojet                                                                                                                                                                         
2020                                                                                                            .    BioJet_20                .    BIOMASS_BJ      .    IFLOWINOUT_IN 
2020                                                                                                            .    BioJet_25                .    BIOMASS_BJ      .    IFLOWINOUT_IN 
2020                                                                                                            .    BioJet_30                .    BIOMASS_BJ      .    IFLOWINOUT_IN 
2020                                                                                                            .    BioJet_35                .    BIOMASS_BJ      .    IFLOWINOUT_IN 
2020                                                                                                            .    BioJet_40                .    BIOMASS_BJ      .    IFLOWINOUT_IN 
2020                                                                                                            .    BioJet_45                .    BIOMASS_BJ      .    IFLOWINOUT_IN 
2020                                                                                                            .    BioJet_50                .    BIOMASS_BJ      .    IFLOWINOUT_IN 
                                                                                                                                                                                      
2020                                                                                                            .    BioJet_H2_20             .    BIOMASS_BJ_H2   .    IFLOWINOUT_IN 
2020                                                                                                            .    BioJet_H2_25             .    BIOMASS_BJ_H2   .    IFLOWINOUT_IN 
2020                                                                                                            .    BioJet_H2_30             .    BIOMASS_BJ_H2   .    IFLOWINOUT_IN 
2020                                                                                                            .    BioJet_H2_35             .    BIOMASS_BJ_H2   .    IFLOWINOUT_IN 
2020                                                                                                            .    BioJet_H2_40             .    BIOMASS_BJ_H2   .    IFLOWINOUT_IN 
2020                                                                                                            .    BioJet_H2_45             .    BIOMASS_BJ_H2   .    IFLOWINOUT_IN 
2020                                                                                                            .    BioJet_H2_50             .    BIOMASS_BJ_H2   .    IFLOWINOUT_IN 
                                                                                                                                                                                      
***************************************************************************************                                                                                               
                                                                                                                                                                                      
2020                                                                                                            .    EMethanol_synthesis_20   .    EMETHANOLFLOW   .    IFLOWINOUT_OUT
2020                                                                                                            .    EMethanol_synthesis_25   .    EMETHANOLFLOW   .    IFLOWINOUT_OUT
2020                                                                                                            .    EMethanol_synthesis_30   .    EMETHANOLFLOW   .    IFLOWINOUT_OUT
2020                                                                                                            .    EMethanol_synthesis_35   .    EMETHANOLFLOW   .    IFLOWINOUT_OUT
2020                                                                                                            .    EMethanol_synthesis_40   .    EMETHANOLFLOW   .    IFLOWINOUT_OUT
2020                                                                                                            .    EMethanol_synthesis_45   .    EMETHANOLFLOW   .    IFLOWINOUT_OUT
2020                                                                                                            .    EMethanol_synthesis_50   .    EMETHANOLFLOW   .    IFLOWINOUT_OUT
                                                                                                                                                                                      
2020                                                                                                            .    EMethanol_Upgrade_20     .    EME_DROPIN_FLOW .    IFLOWINOUT_OUT
2020                                                                                                            .    EMethanol_Upgrade_25     .    EME_DROPIN_FLOW .    IFLOWINOUT_OUT
2020                                                                                                            .    EMethanol_Upgrade_30     .    EME_DROPIN_FLOW .    IFLOWINOUT_OUT
2020                                                                                                            .    EMethanol_Upgrade_35     .    EME_DROPIN_FLOW .    IFLOWINOUT_OUT
2020                                                                                                            .    EMethanol_Upgrade_40     .    EME_DROPIN_FLOW .    IFLOWINOUT_OUT
2020                                                                                                            .    EMethanol_Upgrade_45     .    EME_DROPIN_FLOW .    IFLOWINOUT_OUT
2020                                                                                                            .    EMethanol_Upgrade_50     .    EME_DROPIN_FLOW .    IFLOWINOUT_OUT
                                                                                                                                                                                      
2020                                                                                                            .    E_FT_20                  .    E_FT_SUM_FLOW   .    IFLOWINOUT_OUT
2020                                                                                                            .    E_FT_25                  .    E_FT_SUM_FLOW   .    IFLOWINOUT_OUT
2020                                                                                                            .    E_FT_30                  .    E_FT_SUM_FLOW   .    IFLOWINOUT_OUT
2020                                                                                                            .    E_FT_35                  .    E_FT_SUM_FLOW   .    IFLOWINOUT_OUT
2020                                                                                                            .    E_FT_40                  .    E_FT_SUM_FLOW   .    IFLOWINOUT_OUT
2020                                                                                                            .    E_FT_45                  .    E_FT_SUM_FLOW   .    IFLOWINOUT_OUT
2020                                                                                                            .    E_FT_50                  .    E_FT_SUM_FLOW   .    IFLOWINOUT_OUT
                                                                                                                                                                                      
2020                                                                                                            .    Ammonia_Synthesis_20     .    AMMONIA_FLOW    .    IFLOWINOUT_OUT
2020                                                                                                            .    Ammonia_Synthesis_25     .    AMMONIA_FLOW    .    IFLOWINOUT_OUT
2020                                                                                                            .    Ammonia_Synthesis_30     .    AMMONIA_FLOW    .    IFLOWINOUT_OUT
2020                                                                                                            .    Ammonia_Synthesis_35     .    AMMONIA_FLOW    .    IFLOWINOUT_OUT
2020                                                                                                            .    Ammonia_Synthesis_40     .    AMMONIA_FLOW    .    IFLOWINOUT_OUT
2020                                                                                                            .    Ammonia_Synthesis_45     .    AMMONIA_FLOW    .    IFLOWINOUT_OUT
2020                                                                                                            .    Ammonia_Synthesis_50     .    AMMONIA_FLOW    .    IFLOWINOUT_OUT
                                                                                                                                                                                      
                                                                                                                                                                                      
/                                                                                                                                                                                     
;                                                                                                                                                                                     
                                                                                                                                                                                      
PROCKAPDATA(Y,PROC,FLOW,IFLOWINOUT)=PROCKAPDATA('2020',PROC,FLOW,IFLOWINOUT);                                                                                                         
