PARAMETER FLOWSHAREIN2IN(YYY,AAA,PROC,IFLOWIN,IFLOWIN2,ILOUPFXSET) "Relationship between two input flows (U1/U2) - units of flow 1 divided by units of flow 2"
/                                                                                                                                                             
                                                                                                                                                              
                                                                                                                                                              
/                                                                                                                                                             
;                                                                                                                                                             
