SET AAATRANSIT(AAA)   'Areas that are for waste transit only'
/                                                            
*DK1_Large                                                   
*DK2_Large                                                   
*NO1_A2                                                      
*NO1_A3                                                      
*SE3_large                                                   
*SE3_medium                                                  
*SE4_large                                                   
*SE4_medium                                                  
*UK_A                                                        
                                                             
                                                             
                                                             
                                                             
/;                                                           
