SET PROCSTORAGE(PROC) "Storage processes"
                                         
/                                        
                                         
                                         
                                         
                                         
Biogas_Grid_STO                          
CO2_Sto                                  
/;                                       
